### ISSUE TITLE
Animations/Sounds not working

### ISSUE THREAD

**Issue by Gunbunny** [wrycu/StarWarsFFG-Enhancements#156] opened 2023-02-20 03:09 UTC
FFG-Enhancements 2.01, Foundry 10.291, Star Wars alpha 8 along with JBA 0.5.4.  When selecting offensive token, targeting defender, and rolling weapon from inventory no sounds/bolts, etc. are shown.  Just the dice rolling.  Do have Dice So Nice.

Saw red text referring to ffg-gui, and one for enhancement:

Uncaught (in promise) TypeError: tokenDoc is undefined
[Detected 2 packages: statuscounter, ffg-star-wars-enhancements]
    EffectCounter https://play.gunbunnyfufu.com/modules/statuscounter/module/api.js:32
    update_status https://play.gunbunnyfufu.com/modules/ffg-star-wars-enhancements/scripts/talent_checker.js:175
    update_minion_status https://play.gunbunnyfufu.com/modules/ffg-star-wars-enhancements/scripts/minionsize_sync.js:73
    minionsize_sync https://play.gunbunnyfufu.com/modules/ffg-star-wars-enhancements/scripts/minionsize_sync.js:41
    <anonymous> https://play.gunbunnyfufu.com/modules/ffg-star-wars-enhancements/ffg-star-wars-enhancements.js:133
    #call https://play.gunbunnyfufu.com/scripts/foundry.js:724
    callAll https://play.gunbunnyfufu.com/scripts/foundry.js:681
    _onUpdateTokenActor https://play.gunbunnyfufu.com/scripts/foundry.js:22508
    _onUpdate https://play.gunbunnyfufu.com/scripts/foundry.js:22369
    callback https://play.gunbunnyfufu.com/scripts/foundry.js:12823
    documents https://play.gunbunnyfufu.com/scripts/foundry.js:12804
    _handleUpdateEmbeddedDocuments https://play.gunbunnyfufu.com/scripts/foundry.js:12804
    _updateEmbeddedDocuments https://play.gunbunnyfufu.com/scripts/foundry.js:12672

Not sure if that helps.  Happy to help troubleshoot.

**Comment by wrycu** [comment] 2023-03-01 05:03
I can't reproduce. Do you have more detailed steps to cause the error?

**Comment by Gunbunny** [comment] 2023-03-05 23:14
Sorry for the late response.  I don’t have specific steps…it just doesn’t seem to work.  I can certainly make you a GM so that you can see what I’m talking about if you like on my server.  However, whatever I need to do in order to get it to work.  Happy to help in whatever way.

**Comment by wrycu** [comment] 2023-07-09 22:23
Closing since I can't reproduce. If you continue to see the issue, please file a new issue with step-by-step reproduction steps so I can look into it.

**Closed by wrycu** 2023-07-09 22:23 UTC
Labels: cannot reproduce
