### ISSUE TITLE
Module Won't Activate for JB2A Patreon Subscribers

### ISSUE THREAD

**Issue by AtreidesGhola** [wrycu/StarWarsFFG-Enhancements#35] opened 2021-05-20 20:18 UTC
As mentioned in the Discord channel - I have the Patreon version of JB2A animated assets, and the module prevents loading if it can't find the free version.
![NotWorking](https://user-images.githubusercontent.com/66924036/119043461-1214ab00-b987-11eb-8e6d-b6c770145616.PNG)

**Comment by wrycu** [comment] 2021-05-20 23:35
dupe of #27; just awaiting release

**Closed by wrycu** 2021-05-20 23:35 UTC
Labels: bug, duplicate
