### ISSUE TITLE
[Compatability] JB2A Patreon Pack

### ISSUE THREAD

**Issue by Havoclivekiller** [wrycu/StarWarsFFG-Enhancements#27] opened 2021-05-19 05:26 UTC
I've the patreon pack of JB2A animations but the module requires me to use the non-patreon version. Won't launch without it.

**Comment by wrycu** [comment] 2021-05-19 06:07
Yeah, I'm looking for a better solution for this.  The problem is that you can't declare optional dependencies and can't allow >1 module to fulfil a dependency.  The other way I can think of doing it is to not require JB2A at all, but that results in a worse UX for users who don't have either. 

I'm open to ideas on how to solve this, if you have any.

**Comment by Havoclivekiller** [comment] 2021-05-19 06:13
My suggestion is to remove the dependency. Have a popup when a Gamemaster logs in with the Star Wars Enhancement info, there you could have a warning that the module has animations but needs JB2A pack (patreon or not). Disable all animations until the module detects the JB2A is activated.

**Comment by wrycu** [comment] 2021-05-19 18:19
Done. Will be released in `0.1.8`.

**Closed by wrycu** 2021-05-19 18:19 UTC
Labels: enhancement
