### ISSUE TITLE
music stops before the clip is done

### ISSUE THREAD

**Issue by llothos** [wrycu/StarWarsFFG-Enhancements#78] opened 2021-12-08 05:58 UTC
I have a recording of star wars theme about 1:30 and the music cuts out around 50 seconds and text continues until where it gets cut short (as other bug already reported).

**Comment by wrycu** [comment] 2021-12-08 06:00
Thanks for the report!

What version of the module, system, and foundry are you using?

**Comment by llothos** [comment] 2021-12-08 06:14
using .8.9 with 1.6 and doesn't say there are any module updates. (module was installed fresh).
I was using the forge hosting when I reported the issue so I did another test on my desktop client to see if there was anything different and on that it played right through correctly. Also using identical version of everything so maybe it's some issue with browser (chrome/chromium) and forge?

**Comment by wrycu** [comment] 2021-12-08 16:50
What's the contents of your intro? I wasn't able to reproduce it with self hosting and the default intro.

**Comment by llothos** [comment] 2021-12-08 20:55
I was using the forge hosting when I reported the issue so I did another test on my desktop client (self hosted) to see if there was anything different and on that it played right through correctly. Also using identical version of everything so maybe it's some issue with browser (chrome/chromium) and forge?

**Comment by wrycu** [comment] 2021-12-10 17:26
Must be. I'm going to close this since I can't reproduce it; if you find out more, feel free to re-open.

**Closed by wrycu** 2021-12-10 17:26 UTC
Labels: bug
